name = "aimsync"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "aimsync-db"
database_id = "4c10d76d-d19f-4372-925a-565ad2d31912"

[vars]
GITHUB_REPO_OWNER = "LogicArchitectDS"
GITHUB_REPO_NAME = "AimSync"

[observability]
enabled = true
